/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const RestaurantInfo = IDL.Record({
  'hours' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [], []),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [IDL.Opt(RestaurantInfo)], ['query']),
  'getSpecialties' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'setRestaurantInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setSpecialties' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const RestaurantInfo = IDL.Record({
    'hours' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [IDL.Opt(RestaurantInfo)], ['query']),
    'getSpecialties' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setRestaurantInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setSpecialties' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };